### ISSUE TITLE
id and isMso on the same line accepted

### ISSUE THREAD

**Issue by GimmeChowder** [fernandreu/office-ribbonx-editor#114]
Validate did not catch this line:

<button id="btnInsertShiftDown" idMso="FillDown" label="Shift Down" onAction="rbnGCL.grpCellsCallback" />

Should have been imageMso instead of idMso.

**Comment by fernandreu** [comment]
I think the problem might be that, with both attributes present, it is still correct in terms of the XML Schema (which is what it is being validated against), but Excel might apply some extra validation. I'll see what I can do.

**Comment by GimmeChowder** [comment]
No problem. I'm just trying to be a good user and report what I see.

Thanks,

Al Sim
Web Project Manager
ValuSource

**Comment by fernandreu** [comment]
And that's definitely appreciated, thanks!

**Comment by fernandreu** [comment]
I have made some changes to also detect groups of mutually exclusive attributes as part of the validation process. There are actually quite a few of those, mostly because of the `getX` ones (e.g. `label` and `getLabel`). You can see those groups [here](https://github.com/fernandreu/office-ribbonx-editor/blob/a56f842217ee7f60cd1e233be433e7405f88ffa2/src/OfficeRibbonXEditor/Helpers/Xml/XmlValidation.cs#L16). The list might not be 100% correct yet, so there might be some false positives or undetected errors.

[This build](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=907&view=artifacts&type=publishedArtifacts) has these changes implemented.

**Comment by GimmeChowder** [comment]
Thanks for letting me know.

Al Sim
Web Project Manager
ValuSource
