### ISSUE TITLE
Duplicate arguments cause ribbon not to appear (e.g., label and getLabel)

### ISSUE THREAD

**Issue by JonPeltier** [fernandreu/office-ribbonx-editor#137]
**Describe the bug**
If the code for a control has both a regular property and a callback for the same property, the code is validated ("well-formed") but the ribbon does not appear in the host application.

**To Reproduce**
Sample code that is validated as "well-formed" but causes ribbon not to appear.
<button id="btnLockLimits1" label="Lock Limits" getLabel="GetLabelLockLimits" imageMso="SheetProtect" size="large" onAction="OnActionLockLimits" />

**Expected behavior**
If I validate the code, I would expect the duplicate properties to be flagged. The validation routine should test for such duplication,

**Comment by fernandreu** [comment]
Hi JonPeltier, this should be the same bug as in #114 and is already fixed in the latest development build. I'll create a formal release one of these days but, in the meantime, feel free to download that build from [here](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=969&view=artifacts&pathAsName=false&type=publishedArtifacts). If you find any `xyz` / `getXyz` pair still passing the validation, just let me know.

**Comment by JonPeltier** [comment]
Thanks. I'll check it out.
