### ISSUE TITLE
zh-CN translation

### ISSUE THREAD

**Issue by bitaller** [fernandreu/office-ribbonx-editor#139]
I'd like to contribute on zh-CN translation.

**Comment by fernandreu** [comment]
Hi bitaller, that would be awesome, thanks! Would you like me to create the baseline `Strings.zh-CN.resx` file that will need to be translated, or are you happy to do that yourself based on the instructions in [here](https://github.com/fernandreu/office-ribbonx-editor#creating-a-translation-for-a-new-language)?

**Comment by bitaller** [comment]
It would be great if you create the baseline Strings.zh-CN.resx file. btw, I haven't seen "language" setting on the menu.

**Comment by fernandreu** [comment]
That's the development build done with the translation added. It's available here: https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=977&view=artifacts&pathAsName=false&type=publishedArtifacts

A few notes:
- As I mentioned in #140, I added your username to both the GitHub README (at the bottom) and the About dialog in the tool, with a link to your GitHub profile. If you want me to change that to a different username, link (or not mentioning anything at all), I'm happy to change it
- I added an extra `About.Translators` entry for the `Translators:` header in the About dialog, in case you want to translate that as well ([here](https://github.com/fernandreu/office-ribbonx-editor/blob/1699d150efb53b3289e26e039d9b29305a46f1c4/src/OfficeRibbonXEditor/Resources/Strings.zh-CN.resx#L766))
- There are a few items which are not supported for translation and will remain in English, either because it would be difficult or because I decided it would be best. These are the right-click menu entries of the editor and the *legal* text at the bottom of the About dialog

![image](https://user-images.githubusercontent.com/2480661/105915070-2b37cb80-6027-11eb-9e19-569cd96c2a78.png)

![image](https://user-images.githubusercontent.com/2480661/105915090-38ed5100-6027-11eb-8519-7e36827078ee.png)
