### ISSUE TITLE
Problem after windows update 2021-04-15

### ISSUE THREAD

**Issue by jasell** [fernandreu/office-ribbonx-editor#152]
**Describe the bug**
We have created ribbon add-in for Excel, Word and Power point for ver 16 (customUI14.xml).

After windows updated today we started to get problems through out our company.
Word and Excel are failing, they are crashing with our addin enabled.

If we disable the add-in everything works fine.

We have tried to completely re-install the office suite but now difference.

I created also the most simple add-in, a ribbon with one group, one tab, one control, and still have this problem.

**Additional context**
MS office 365 ver  16.0.14007.2

**Comment by jasell** [comment]
OK, I googled around a bit and found hints that the OSF.DLL file could cause such problems.
The suggested solution were to delete the file and use your add-ins.

This solution worked for me, but I have no idea what that file were supposed to do, and if I'm missing some vital part of office now.

**Comment by fernandreu** [comment]
Hi jassel,

I'm afraid I can't be of much help with an issue like that. This tool doesn't do anything very *special*: it just unzips your Office document, puts the `customUI14.xml` file inside and zips it back. It shouldn't cause any changes to any of your existing dlls, or programs in general. To double-check, you could also do the process of adding the Custom UI file manually instead of relying on this tool, and see if Office still crashes with the resulting add-in.

It sounds like something got corrupted during that Windows update which was needed by Microsoft Office in order to make the add-ins work. Hence, I think you might have better luck asking for help with either Windows or Microsoft Office itself, either in their official support sites or in some community sites (e.g. [/r/excel](https://www.reddit.com/r/excel/)).
