### ISSUE TITLE
Questions regarding translations

### ISSUE THREAD

**Issue by Claythve** [fernandreu/office-ribbonx-editor#163]
Hi, I just have two questions regarding the translation:
- Why is there a _ in the value field from time to time?
- What does invariant, multiline and singleline mean in the FindReplaceDialog?

**Comment by fernandreu** [comment]
Hi Claythve,

- The underscores are the shortcuts for the top-level menu, which appear when you press the Alt key. You have to put these before the letter you want to use as shortcut. Feel free to modify those as part of a translation; just try not to have the same shortcut for two elements (although the app shouldn't crash due to that). An English example: if you press Alt, `File` in the menu will appear with an underscore under the `F` because its value field is `_File`. If you press `Alt+F`, the menu will open
- These are all settings which are common when dealing with regular expressions, and alter the way in which the matches are found. The invariant one might be a bit more C#-specific though. You can read a bit about those in [here](https://docs.microsoft.com/en-us/dotnet/standard/base-types/regular-expression-options) (this might be a good source to find translations for these too actually, e.g. [this](https://docs.microsoft.com/de-DE/dotnet/standard/base-types/regular-expression-options)). By the way, you just made me find bug #165 😇

On a similar note, I've just added two new keys, in case you want to translate them in German: [Message.CorruptedSettings.Text](https://github.com/fernandreu/office-ribbonx-editor/blob/176e0495d118828bfad6102ae17bf456611b9377/src/OfficeRibbonXEditor/Resources/Strings.de-DE.resx#L768) and [Message.CorruptedSettings.Title](https://github.com/fernandreu/office-ribbonx-editor/blob/176e0495d118828bfad6102ae17bf456611b9377/src/OfficeRibbonXEditor/Resources/Strings.de-DE.resx#L775). I wouldn't expect users to ever see this message if the tool works correctly anyway.

**Comment by Claythve** [comment]
Hi Fernando,
thank you very much for the quick reply. I will update the translation and add the two keys.
