### ISSUE TITLE
Add more translation options

### ISSUE THREAD

**Issue by llnulldisk** [fernandreu/office-ribbonx-editor#167]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The possibility to add a translation for the following things:
- Settings.Colors: color names
- Settings.Editor.WrapMode: choices from drop down
- FindReplace.Options: options when standard is selected
- Menu.Insert.Sample: name of sample
- MessageBox buttons

**Describe alternatives you've considered**
These are only suggestions. If something doesn't make sense or is too much work, it's not a problem. Optionally I could implement it myself

**Comment by fernandreu** [comment]
Hi Claythve,

- **Color names:** It's possible that the translations already exists for that control and I just need to switch them on. However, there's a paid version of that control which usually allows more customisation (like styles), so I'm suspecting that it might be limited to that version. Otherwise, it might be a bit too challenging to implement myself, and it's probably a better idea to get rid of that control and find an alternative. I´ll have a look
- **Wrap modes:** Not a problem. Perhaps I missed them originally. Perhaps I thought it would be difficult to implement, but I am now quite certain there's no obstacles for it
- **Standard find / replace options:** I totally missed those. I'll add them
- **Sample names:** Yeah, I can probably do something about this. The main challenge is the fact that you can define your custom samples too, so the tool has to know when to translate them and when not. But I have a pretty good idea of how to achieve that
- **MessageBox buttons:** This is actually working fine, but probably not in the way you would expect. The translations for these buttons are automatically provided by the framework (WPF / .NET). However, the language in which they are shown is based on the Windows language, not on the tool´s, and I do not have control over that. It might look a bit funny to have buttons in a language and the tool in another but, ultimately, the user should be using Windows in a language they understand, so they should have no issues understanding the choices either. The main alternative is probably to roll my own dialog to be used instead of all those all those standard message boxes, but it is probably a bit of an overkill

**Comment by llnulldisk** [comment]
Hello fernandreu,
Sorry, I see I never actually answered you here :D In my opinion, the issue is now resolved. The error with the MessageBox buttons is my fault, because I had Windows in English. And you've already dealt with the other points
