### ISSUE TITLE
Add-Ins information is show below the tooltip

### ISSUE THREAD

**Issue by bjkluft** [fernandreu/office-ribbonx-editor#170]
**Describe the bug**
First I'm not completly sure this is an issue with the Ribbon editor, but I only see it on custom created buttons.
The issue that when you hover over an custom button it shows the Add-Ins information of Excel/Office below the screentip:

**Expected behavior**
I would like this to be gone. So on hover over a button only show the screentip and not de Add-Ins info.

**Screenshots**
![Add-Ins-Ribbon_Editor](https://user-images.githubusercontent.com/12735834/123262200-e9d51a80-d4f7-11eb-85e3-79fb222f8419.png)

Kind regards,
Jeroen

**Comment by fernandreu** [comment]
Hi Jeoren,

Unfortunately this is standard Office behaviour, so there's nothing the editor can do about it. I have always seen that extra information on buttons coming from add-ins, so I imagine it is some sort of "disclaimer" for the users to know that what they are about to press isn't coming straight from Microsoft.

There might be some way to turn it off, but I haven't really tried looking into that before. If it exists, it is probable that each user would have to do this individually, rather than being driven automatically from your add-in.

**Comment by bjkluft** [comment]
Thank you for your reply.
I've found some more information and it is indeed a security issue from Microsoft. Meant to let the user know he/she is using a third-party add-on.
