### ISSUE TITLE
Save changes prompt not working correctly

### ISSUE THREAD

**Issue by jkpieterse** [fernandreu/office-ribbonx-editor#172]
I am using RibbonX editor (THANK YOU!) and found a small bug: If you have multiple (changed) files open and close the aopp, it only asks to save the active window. Changes in other windows are lost.

Version: 1.8.0.990
Runtime:
 .NET 5.0.7
 Operating System: Microsoft Windows 10.0.19042

**Comment by fernandreu** [comment]
Hi @jkpieterse, thanks for letting me know, and sorry for the delay answering (I completely forgot). This was caused by the tool incorrectly applying the save action to the currently active document, instead of applying it to the document whose save changes dialog just appeared.

It should be fixed in this build: https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=1040&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by jkpieterse** [comment]
Hi Fernando,

 

Thanks!

Not being familiar with that interface, which item do I need to get the installer?

 

Regards,

 

Jan Karel Pieterse

JKP Application Development Services

The Netherlands

Chamber of Commerce # 12052177

https://www.jkp-ads.com

Phone: +31 495 750546

Mobile: +31 648 628252

**Comment by fernandreu** [comment]
There is a little button at the right which, if you press it, it will give you a download option:

![image](https://user-images.githubusercontent.com/2480661/127223284-4167a3b0-ba97-483e-b327-a77691904186.png)

(It's a little subtle yeah)

Feel free to download any of the variants in there. You should see one variant for each downloadable item which is usually available on a normal release (e.g. [here](https://github.com/fernandreu/office-ribbonx-editor/releases/tag/v1.8.0)) - plus a code coverage item that you can safely ignore.

**Comment by jkpieterse** [comment]
Hi Fernando,

 

Got it, thanks!

 

Regards,

 

Jan Karel Pieterse

JKP Application Development Services

The Netherlands

Chamber of Commerce # 12052177

https://www.jkp-ads.com

Phone: +31 495 750546

Mobile: +31 648 628252
