### ISSUE TITLE
Sort List of included Icons alphabetically

### ISSUE THREAD

**Issue by pm-braun** [fernandreu/office-ribbonx-editor#189]
**Is your feature request related to a problem? Please describe.**
I have included many icons into my RibbonX XML and if I search for one it is diffucult, because the list is not sorted aplhabetically

**Describe the solution you'd like**
Sort the list of the included icons alphabetically

**Describe alternatives you've considered**
Sorting could be made optional via settings.

**Additional context**
Example of my list of Icons - unsorted
![image](https://user-images.githubusercontent.com/94298607/141683130-e1786f3c-296d-468c-815a-d2a287b013a5.png)

**Comment by pm-braun** [comment]
Thank you very much Fernando!
That is really appreciated.
When do you plan to deploy the next Version of RibbonX Editor - no hurries ;-)
Best
Patrick

**Comment by fernandreu** [comment]
Hi Patrick, it will probably take some time until I deploy another release, as I just deployed one and I don't want to annoy people too often with newer versions if they don't have big changes. Unless I find a really serious bug which I consider everybody should get rid of, in which case I might produce a version 1.9.1 much more quickly. However, there have been some important changes since that release (namely the lack of both a .NET Framework build and a trusted code-signing certificate), so the next version should probably be 2.0.

Anyway, in the meantime, you can always get the latest [development builds](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/latest?definitionId=1&branchName=master), and it will contain your feature. For example, this one:
https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=1123&view=artifacts&pathAsName=false&type=publishedArtifacts

The only difference respect to a full release is the fact that the new features might have introduced some side effects which I didn't find yet (but it could also happen with full releases really).

**Comment by pm-braun** [comment]
Hi Fernando,
thanks very much for your detailed explanation and the links you mention!
Although I was not able to figure out how to get the development build "installed" when I click on either of the links below, which appear after clicking on your link https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=1123&view=artifacts&pathAsName=false&type=publishedArtifacts:

![2021-11-28 21_25_45-Pipelines - Run 20211118 4 artifacts](https://user-images.githubusercontent.com/94298607/143784700-f1a46b70-d532-4783-84a4-f2002bdeac04.png)

Any help is appreciated - but again: no hurries ;-)
Best Patrick

**Comment by fernandreu** [comment]
At the right side of each element, there is a button with an ellipsis which is only visible when hovering the mouse over that element. This will give you the option to download the files:

![image](https://user-images.githubusercontent.com/2480661/143785705-aa4e95ad-3851-46d5-af39-43e8ee15581d.png)

Not the most intuitive UI yeah, a bit too subtle. Oddly enough, when you are logged in there, the artifacts become drop downs where you can check the files they contain and download them individually too:

![image](https://user-images.githubusercontent.com/2480661/143785630-6e51fc61-0d74-4c57-92c1-3e0e515ce3b1.png)

Or maybe this only shows for me, since I am the owner of that pipeline.

**Comment by pm-braun** [comment]
Hi Fernando,
thank you very much for the prompt answer - that was easy. I must have been blind. 😑
Nevertheless the new feature works perfctly - thanks again!
Best
Patrick
