### ISSUE TITLE
Method not found

### ISSUE THREAD

**Issue by robinboncoeur** [fernandreu/office-ribbonx-editor#48]
**Describe the bug**
Installed OfficeRibbonXEditor-v1.5.msi in Windows 7 Professional, running in a VM (VirtualBox) on a Macbook Pro 2012. After launching Office RibbonX Editor, opened a Excel .xlsm file, and this dialogue appears: 
Dialog Description: 
Error opening Office document

Text in dialogue:
Method not found: 'Microsoft.Win32.RegistryKey
Microsoft.Win32.RegistryKey.CreateSubKey(System.String, Boolean)',

**To Reproduce**
1. Load Office RibbonX Editor
2. Open any Excel .xlsm file - happens consistently
3. See error

**Expected behavior**
This dialogue is of some concern - something that is expected to happen: doesn't.

**Screenshots**

**Additional context**
Clicking OK and carrying on with using the software doesn't appear to have any issues, but I'm concerned that there might be problems when users open the files with customised menus.

**Comment by fernandreu** [comment]
Hi robinboncoeur,

Thanks for letting me know. Currently, the registry is only used to store the list of recent files opened in there (see [this](https://github.com/fernandreu/office-ribbonx-editor/blob/52b99a93d842d1959898c31affd7a5e475c1f084/OfficeRibbonXEditor/Models/RecentFileList.cs#L552)), which would explain why the error occurs right after opening a file. This error should not affect anything else other than the list of recent files itself (which I guess it will be empty for you).

I am not exactly sure of why the method to create registry keys would be missing though. This typically occurs when a dll has a different version than expected, but the dll in question is not shipped with the tool and should come with Windows instead. Perhaps it is due to the sandboxed environment you are using. Out of curiosity, do you know which version of the .NET Framework are you using? The tool targets 4.6.1 but it should run fine in newer versions.

In any case, I can switch to a different approach for storing the recent file list (via [XML files](https://github.com/fernandreu/office-ribbonx-editor/blob/52b99a93d842d1959898c31affd7a5e475c1f084/OfficeRibbonXEditor/Models/RecentFileList.cs#L645)), and the error should go away. I will let you know once I make the switch and test that everything works.

**Comment by fernandreu** [comment]
In fact, can you check if [this build](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=410&view=artifacts) works for you without errors opening files?

**Comment by robinboncoeur** [comment]
Thank you for replying, Fernando. I'll admit that my Windows setup is a bit
unusual, running in VBox and all.
In answer to your question, I sort-of don't seem to have a version of a
.Net Framework. What I do have is displayed in the image I've attached. The
only development I do in Windows is VBA apps in Excel: for Python I use
Linux and the Mac.

As to your solution: worked an absolute treat! No error message, all good.
Thank you for the prompt fix: we can mark this issue resolved. :)
Kind regards,
Rob

**Comment by fernandreu** [comment]
No problem! It seems GitHub has removed the attached image from the email response though.

Nevertheless, I found that [the documentation of that CreateSubKey(string, bool) method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.win32.registrykey.createsubkey?view=netframework-4.8#Microsoft_Win32_RegistryKey_CreateSubKey_System_String_System_Boolean_) explicitly mentions it is available starting with .NET Framework 4.6.

I am guessing that, even if you did not install a .NET Framework explicitly, another program might have done so (it is quite a common thing to happen). However, its version might be lower than 4.6, even though the Office RibbonX Editor is still able to run somehow.

If that is the case, I would recommend downloading the most recent .NET Framework version from [here](https://dotnet.microsoft.com/download/dotnet-framework/net48), as it might help preventing similar errors in the future.
