### ISSUE TITLE
After clicking Save, Office RibbonX Editor closes and does not keep changes

### ISSUE THREAD

**Issue by celiasja** [fernandreu/office-ribbonx-editor#55]
I am trying to create a custom ab in Excel

Steps:
On Office RibbonX Editor:
1. open an xlsm file
2. insert Office Custom UI part (I've tried both 2007+ and 2010)
3. insert sample XML > Excel  A Custom Tab
4. generate callbacks
5. validate
6. save

At this point, Office RibbonX Editor closes. No errors or warnings are displayed.

When opening the xlsm file in Excel no changes were made to the file or the ribbon.

I am using 
Windows 10 64 bit
Office 365 64 bit

Any tip on how to solve this issue is very much appreciated.
Thank you.

**Comment by fernandreu** [comment]
Hi celiasja,

It seems an unhandled exception is occurring that is causing the application to close unexpectedly. Unfortunately, I cannot reproduce the issue, and I cannot track the reason for this without seeing the actual exception. However, with a change I just made, the tool should show a message box with some details whenever this occurs, allowing you to continue with your work.

Could you give this new version a try and, if you now get an error message, let me know what it says?
https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=455&view=artifacts

**Comment by celiasja** [comment]
Wow, Fernando! That’s what it’s called fast response! Thank you!

This is the message error that I got:



 

What do you think might be causing this? Could it be my Antivirus? I am using Bitdefender.

 

Thank you,

 

Celia Alves

Solve & Excel Consulting

 <https://solveandexcel.ca/> solveandexcel.ca | 1-647-882-6285 

 <http://www.linkedin.com/in/celiajordaoalves> Connect on LinkedIn |  <https://www.youtube.com/channel/UCzWFp4hOnIBHHCJi_SEWV7g> YouTube |  <https://www.facebook.com/solveandexcel/> Facebook

**Comment by celiasja** [comment]
Another message:



 

I chose Yes on the message sent on my previous email. Then when closing, it said there were unsaved changes and asked if I wanted to save. I said Yes and got this error message.

This time I chose Yes again and the program closed.

 

As expected, no changes were made to the xlsm file.

 

Thank you,

 

Celia Alves

Solve & Excel Consulting

 <https://solveandexcel.ca/> solveandexcel.ca | 1-647-882-6285 

 <http://www.linkedin.com/in/celiajordaoalves> Connect on LinkedIn |  <https://www.youtube.com/channel/UCzWFp4hOnIBHHCJi_SEWV7g> YouTube |  <https://www.facebook.com/solveandexcel/> Facebook

 

From: Celia Alves <celia.alves.biz@gmail.com> 
Sent: October 11, 2019 12:59 PM
To: 'fernandreu/office-ribbonx-editor' <reply@reply.github.com>; 'fernandreu/office-ribbonx-editor' <office-ribbonx-editor@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [fernandreu/office-ribbonx-editor] After clicking Save, Office RibbonX Editor closes and does not keep changes (#55)

 

Wow, Fernando! That’s what it’s called fast response! Thank you!

This is the message error that I got:



 

What do you think might be causing this? Could it be my Antivirus? I am using Bitdefender.

 

Thank you,

 

Celia Alves

Solve & Excel Consulting

 <https://solveandexcel.ca/> solveandexcel.ca | 1-647-882-6285 

 <http://www.linkedin.com/in/celiajordaoalves> Connect on LinkedIn |  <https://www.youtube.com/channel/UCzWFp4hOnIBHHCJi_SEWV7g> YouTube |  <https://www.facebook.com/solveandexcel/> Facebook

**Comment by fernandreu** [comment]
Hi Celia,

Sorry, I cannot see the pictures that (I assume) you posted. This is because GitHub removes them when the message gets added to the issue ([here](https://github.com/fernandreu/office-ribbonx-editor/issues/55)).

Could you upload them to some free service such as [Imgur](https://imgur.com/upload) and pass me the links instead?

Regards,
Fernando

**Comment by celiasja** [comment]
Thank you for letting me know, Fernando.

Please see this link: https://www.dropbox.com/s/h7ihrepmxyqhbvx/errorMsg.png?dl=0

I hope it works.

Thank you,

 

Celia Alves

**Comment by celiasja** [comment]
I am sorry for such long posts. I have been responding directly from my email. The next time, I will come to anser directly here.

**Comment by fernandreu** [comment]
Hi Celia,

Thanks for the screenshots, and don't worry about the long posts!

The antivirus might have something to do, but I am more inclined to think it is a permissions issue with Windows (perhaps due to changes made by Dropbox).

I don't think the issue will be that the file is read-only because that does not give any error message (but it should; I will fix that). However, do you actually have write access to that file? I.e. if you check Properties -> Security for that file, does it show you something like this for your user?

![image](https://user-images.githubusercontent.com/2480661/66687663-5902d080-ec7b-11e9-8b0f-8b51984ea2fb.png)

That is the only way I found so far to replicate the exact same issue: removing the write permissions from myself.

If this is the case, one of the following should fix the issue:

- Add write permissions to that file
- Run the tool as administrator
- Save the file in a different path (with write access)

From the tool side, there isn't anything I can do to fix the issue, but I will definitely try to detect this situation a bit better and have have a clearer error message when it occurs.

Regards,
Fernando

**Comment by celiasja** [comment]
Hi Fernando!

The file access properties were ok. The System and I were both defined to have full access to the file.
Dropbox was causing the issue. When I moded the file out of the Dropbox folder, Office RibbonX Edition stopped crashing on saving, and the changes were now kept on the file. So, thank you for that tip! Problem solved!

On another note, when adding a part for 2007, and then the XML code for an Excel Tab, the code generated comes with 
<customUI xmlns="http://schemas.microsoft.com/office/2009/07/customui">
When I click Validate, no error is reported. Then, opening the xlsm file, the ribbon was not there.
I went back to the code and changed it to <customUI xmlns="http://schemas.microsoft.com/office/2006/01/customui"> and the ribbon became visible.

The old CustomUI Editor would notice that error on Validation. I am leaving a link for a video showing that in case you want to incorporate that in the next update: https://www.youtube.com/watch?time_continue=3&v=ZTt2FFyj2Fo

Thank you so much for your quick and efficient support! Kudos to you!

**Comment by fernandreu** [comment]
Glad you found out the issue! Good catch about the XML namespace too. I have now added that check to the latest build ([here](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=459&view=artifacts)). At some point, I will also try to adjust the template namespace automatically depending on the part where it is being inserted.

**Comment by celiasja** [comment]
Thank you, Fernando, for the fantastic service that you provide to the community.
