### ISSUE TITLE
Latest Version?

### ISSUE THREAD

**Issue by phossler** [fernandreu/office-ribbonx-editor#78]
I have version 1.5.1.463 according to Help-About

But at
https://github.com/fernandreu/office-ribbonx-editor

"To download the latest release, go to the following link:
https://github.com/fernandreu/office-ribbonx-editor/releases/latest

it takes me to 1.5.1.418 (August 13)

I'm GitHub challenged, so where is the latest release located?

Thanks

**Comment by fernandreu** [comment]
Hi phossler,

There are two types of ways of getting the tool (both mentioned in the main project page):

- From [GitHub's releases page](https://github.com/fernandreu/office-ribbonx-editor/releases) as you mentioned
- From [Azure Pipelines](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/latest?definitionId=1&branchName=master)

The latter is a development build, in the sense that one new version gets automatically generated as soon as I make some changes to the master branch of the project. You usually get more bugs fixed in those, which is why I normally suggest people to download one of those after I have completed an issue they created (in your case, see [this](https://github.com/fernandreu/office-ribbonx-editor/issues/59)).

The downside of those development builds is that, if I have just made recent changes to the tool, there might also be new bugs introduced that I have not fixed yet. I create releases at a much slower pace than development builds mainly because of this (and also to avoid annoying users with too many _Version x.y.z available!_ messages :sweat_smile:).

The first three digits (1.5.1) are manually changed by myself before pushing the changes to the repository. The fourth version digit (463 in your case) will automatically refer to the build ID. You can see the most recent builds [here](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build?definitionId=1&_a=summary). The build ID appears in the URL of each build; [482](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=482&view=results) is currently the latest. I am just preparing for another release in the next few weeks, so the development build should be quite stable.

You can only see builds from the last 30 days (or associated to a _Release Pipeline_ in Azure, which is not the same as a GitHub Release), so build 463 is no longer in that list.

**Comment by phossler** [comment]
Thanks for taking the time to explain

 

1. 1.5.1.xxx is the latest ‘official’ release, and I have that 😊

 

Download / Build status

To download the latest release, go to the following link:

 <https://github.com/fernandreu/office-ribbonx-editor/releases/latest> https://github.com/fernandreu/office-ribbonx-editor/releases/latest

To download the latest development build instead, go to the Artifacts section on Azure Pipelines:

 <https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/latest?definitionId=1&branchName=master> https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/latest?definitionId=1&branchName=master

 

 

2. The first link takes me to 418 and [Assets] has the EXE and MSI  😊 😊

 

3. I did try Azure but I could not see any ‘Artifacts’ section. Is it labeled a something else? (I did say that I’m only learning GitHub)

 

If I click on [Releases] I can see Release 11 (20190928) but I didn’t any way to download an EXE or MSI

 

 

 

Sorry to be such a bother

 

 

Paul H. Hossler

Valley Forge, PA 

 

 <mailto:phossler@comcast.net> phossler@comcast.net

**Comment by fernandreu** [comment]
No problem!

The Artifacts section is kind of in the middle once you click on a build, not in the left side. See the bottom-right corner of this screenshot:

![Azure pipeline](https://user-images.githubusercontent.com/2480661/69364637-956a1900-0c8a-11ea-96dc-f607c7061732.png)

The Releases section at the left is a different kind of pipeline that I will start using for the next official release on GitHub. It isn't exactly active at the moment (just pointing to a random build).

Finally, since you mention you are learning GitHub, and just in case you did not notice: when you reply to an issue via email, everybody can still see the answer in here, including your signature, email, etc., and with everything formatted pretty badly usually. Sometimes even the entire email chain (other times, GitHub manages to filter that out). I have updated your comment to remove some bits just in case you did not want to share them.

**Comment by phossler** [comment]
Ahh - thanks for both

Paul
