### ISSUE TITLE
Sample subfolders' names not shown

### ISSUE THREAD

**Issue by phossler** [fernandreu/office-ribbonx-editor#83]
In "C:\Program Files (x86)\Office RibbonX Editor\Samples" I created 4 sub folders to arrange my fragments: 2007, 2010, Excel, and Word

The Settings Templates is = "C:\Program Files (x86)\Office RibbonX Editor\Samples"

When I insert a sample, the subfolder name is not displayed, only the main folder, but the subfolder files are displayed and selectable

![Capture](https://user-images.githubusercontent.com/32959671/73082740-0058eb80-3e98-11ea-8279-ee9b19747673.JPG)

I was expecting either the full path "C:\Program Files (x86)\Office RibbonX Editor\Samples\2010" etc. or just the subfolder "2010"

**Comment by fernandreu** [comment]
Hi phossler,

There was a bug with how the folders were displayed, probably because I tested this adding sample folders with trailing backslashes (e.g. `C:\samples\`) but this was not your case. With the latest [build](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=625&view=artifacts&type=publishedArtifacts), this should work in both cases.

I think my original intention was to show the full folder path, but it is probably nicer if just the folder name is shown, so I will stick with that for now. Perhaps I will add a setting for that later, or for allowing custom names for each folder.

Regards,
Fernando

**Comment by phossler** [comment]
Fast work

Thank you
