### ISSUE TITLE
Add shortcut key to Expand/Collapse Branches

### ISSUE THREAD

**Issue by phossler** [fernandreu/office-ribbonx-editor#86]
Notepad++ has the ability to Expand and Collapse branch using shortcut keys and the [View] menu, including 'All', 'Current', or to a level

Editor has similar capability, but requires clicking the teeny, tiny [+] or [-] box to the left of the line

Adding a [View] menu with similar Notepad++ shortcut key feature would be handy

![Capture](https://user-images.githubusercontent.com/32959671/73550772-2ee44280-4413-11ea-8749-5ac568048369.JPG)

**Comment by fernandreu** [comment]
Hi phossler,

I added a `View` menu in the [latest build](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=630&view=artifacts&type=publishedArtifacts) to show these options. I am having issues assigning the `Unfold Current Level` action to `Ctrl+Alt+Shift+F`, so I assigned it to `Ctrl+Alt+G` instead.

I will leave this issue open for a bit in case I do some tweaks.

Regards,
Fernando

**Comment by phossler** [comment]
I believe that the other 'Unfold' or 'Uncollapse' options include using the Shift key.

So 'Unfold Current Level' might be Ctrl+Alt+Shift+g. Is that what you meant by Ctrl+Alt+G?

**Comment by fernandreu** [comment]
No, `Ctrl+Alt+Shift+[Key]` combinations do not seem to be triggered for some reason (haven't investigated yet either). Hence, rather than `Ctrl+Alt+F` / `Ctrl+Alt+Shift+F` for folding / unfolding respectively, I have mapped the unfold one to `Ctrl+Alt+G`. This is just because it is a similar shortcut to the folding one and the `G` is next to the `F`, no other strong motivation really.

![image](https://user-images.githubusercontent.com/2480661/73773476-23c64500-477a-11ea-876e-d250de336b33.png)

This might just be temporary if I can figure out why the originally intended key combination doesn't work.

**Comment by fernandreu** [comment]
I just had a look at the issue with the `Ctrl+Alt+Shift+F` shortcut, and it seems it is because Windows reserved this particular key combination after an update; see [this](https://superuser.com/questions/1445551/what-does-ctrlaltshiftf-key-combination-in-windows-10-pro-version-1903-do). Other `Ctrl+Alt+Shift+[Key]` combinations are fine.

Notepad++ actually has the exact same problem, so they should probably change this shortcut too. I will create an issue in their project.

Based on that, I think I will leave the shortcut as it is (i.e. `Ctrl+Alt+G`). If Notepad++ does indeed change the shortcut for this, I will make sure this tool uses the same one.
