### ISSUE TITLE
Images - files get renamed even for already existing files

### ISSUE THREAD

**Issue by schroray** [fernandreu/office-ribbonx-editor#98]
**Describe the bug**
Given or inserted images seem to get renamed. This cannot be adjusted or corrected. Logical naming within the editor shows as the names of with original file name. File name within the file gets obfuscated - this applies to existing images in a office file, as well as for newly inserted ones...

**To Reproduce**
1. Go to Open - MyWord.dotm
2. Click on Save or first insert an additional / new image
3. Close file
4. Check structure "customUI/images" - using WinRAR.
5. See renamed files - 'A1.png' becomes '65d25f34-6dc0-4be5-88cb-144157882c2f.png'.

**Expected behavior**
As with the original Editor - no renaming of files.

**Comment by fernandreu** [comment]
Hi schroray,

This was an issue when using the "Reload on Save" option. The file name assigned to the reloaded files was one temporarily generated during the process.

There was also an issue when renaming an icon where the file name would still be the original one. The original editor worked that way, but I would not think this is the behaviour users would expect.

Both issues are fixed in [this build](https://dev.azure.com/fernandreu-public/OfficeRibbonXEditor/_build/results?buildId=729&view=artifacts&type=publishedArtifacts).

**Comment by schroray** [comment]
Thx for your tool in general, your quick help and fix - this works for me!
